services:
  esp8266-am2302:
    container_name: esp8266-am2302
    build:
      context: .
    privileged: true
    environment:
      DB_HOST: timescaledb
      DB_NAME: timescaledb
      DB_USER: timescaledb
      DB_PASS: /run/secrets/db_password
    secrets:
       - db_password
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
       - db_password
    volumes:
      - ./timescaledb-data/timescaledb:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    # ports:
    #   - 5432:5432
    restart: unless-stopped

secrets:
   db_password:
     file: db_pass.secret
